# -*- coding: utf-8 -*-
"""Visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16jn1vthydnlgcVLx4iKE3FCGUWcIJG5D

# **Map Visualizations**
"""

import ee
import geemap
# If not on Colab you'll need install the earth-engine Python API
#!pip install earthengine-api

# Athenticate to your GEE account.
!earthengine authenticate
ee.Initialize()

# Earth Engine Python API
import ee
import geemap
ee.Initialize()

"""# **Mapping Outcomes**"""

Map = geemap.Map()

#Regional Unit: Java

#Strata Map IDs (Classes 1-7):
  #IDN201610S110E ; IDN201610S105E
  #               ; IDN201710S105E
  #IDN201810S110E ; IDN201810S105E
  #IDN201910S110E ; IDN201910S105E
  #IDN202010S110E ; IDN202010S105E
  #IDN202110S110E ; IDN202110S105E

#Land Change Map IDs (Classes 1-13):
  #IDN2016201710S110E ; IDN2016201710S105E
  #IDN2017201910S110E ; IDN2017201910S105E
  #IDN2019202110S110E ; IDN2019202110S105E


#Select East and West maps of interest.
data_1 = ee.Image(
  'projects/ee-martingarciafry/assets/GlobalGroundCoverChange_v1/IndoMalayanEcoZone/Indonesia/Java/IDN202010S110E').select(['b1'])

data_2 = ee.Image(
  'projects/ee-martingarciafry/assets/GlobalGroundCoverChange_v1/IndoMalayanEcoZone/Indonesia/Java/IDN202010S105E').select(['b1'])

#Apply gcc palette for the 13 distinct land cover classes.
gccPalette = [
  '#a99200', # 1. Dense Short Vegetation
  '#0ec149', # 2. Open Tree Forest
  '#04620a', # 3. Dense Tree Forest
  '#78b0ff', # 4. Wetlands
  '#d1dada', # 5. Urban
  '#000367', # 6. Water
  '#cc5902', # 7. Cropland
  '#dd0505', # 8. senescence (strata maps) / Built Loss (change maps)
  '#8e0808', # 9. cultiation (strata maps) / Built Gain (change maps)
  '#fff203', # 10. Cropland Loss (change maps)
  '#e4ce05', # 11. Cropland Gain (change maps)
  '#01f2ff', # 12. Crop>Built (change maps)
  '#06d6d6', # 13. Built>Crop (change maps)
]

Map.setCenter(110.5, -7.4, 7)
vis_params = {'min': 1,
              'max': 13,
              'palette': gccPalette}

Map.addLayer(data_1, vis_params, 'Java East')
Map.addLayer(data_2, vis_params, 'Java West')

Map